### ISSUE TITLE
set STDOUT to file not working

### ISSUE THREAD

**Issue by drakmail** [pyrustic/backstage#1]
I'm trying to set STDOUT to file, execute shell command and read STDOUT of that command from the file:

```ini
[test]
set STDOUT = `/tmp/test.out`
$ echo something

[check]
$ cat /tmp/test.out
```

When I'm running `test` task all seems fine, STDOUT is redirected to somewhere and I got no errors:

```bash
$ backstage test
$
```

But when I'm checking the `/tmp/test.out` file with `something` inside I got `cat: /tmp/test.out: No such file or directory` error:

```bash
$ backstage check
cat: /tmp/test.out: No such file or directory
$
```

I use macOS Monterey 12.3.1, zsh, iTerm2

**Comment by pyrustic** [comment]
Hi !

I managed to reproduce this issue and fixed it. Please upgrade your package: `pip install backstage --upgrade --upgrade-strategy eager`.

Backstage uses [Subrun](https://github.com/pyrustic/subrun) to spawn processes. Subrun assumes that the stdout or stderr argument is an existing file descriptor, an existing file object, a special value such as subprocess.DEVNULL (from a Backstage script, you just need to use the string `/dev/null`, it should also work on Windows), or None.

But the buggy version of Backstage was sending plain paths (normalized, i.e. backslashes are converted to forward slashes if necessary, etc.) strings to Subrun.

Now I make sure Backstage sends a file object to Subrun when you want to perform a redirection. This file will be created if it does not yet exist (idem with its parent directory).

To debug, I put `config ReportException=1 ShowTraceback=1` at the top of the tasks. I think that I should introduce a legit debug mode where the programmer won't need to type this line on top of tasks. The test mode looks fine for the moment.

**Comment by pyrustic** [comment]
There is now a legit debug mode: `backstage -d <task> [<arg> ...]`
Test is still available: `backstage -t [<task> ...]`
Check the new command line interface: `backstage -h`

**Comment by drakmail** [comment]
Thank you, the fix is working!
